language: scala
matrix:
  include:
    - scala: 2.11.12
      jdk: oraclejdk8
      env: PROTO=2.6.1
    - scala: 2.11.12
      jdk: oraclejdk8
      env: PROTO=3.5.1
    - scala: 2.12.5
      jdk: oraclejdk8
      env: PROTO=2.6.1
    - scala: 2.12.5
      jdk: oraclejdk8
      env: PROTO=3.5.1

cache:
  directories:
    - $HOME/.sbt/boot
    - $HOME/.ivy2/cache

script:
  - sbt ++$TRAVIS_SCALA_VERSION -Dprotobuf.version=$PROTO clean coverage test coverageReport

  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" -delete
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    - neville.lyh@gmail.com
